services:
  db:
    image: postgres:15-alpine
    container_name: pdflens-db
    restart: always
    environment:
      # These variables will be pulled from your shell or .env
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234 
      - POSTGRES_DB=PdfLens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdflens-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app:/app/src
    volumes:
      - chroma_data:/app/chroma_db

  frontend:
    build: 
      context: ./frontend
      args:
        # This tells Docker: "Look for a variable called VITE_API_BASE_URL 
        # in my computer's environment (or .env file) and pass it into the build."
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: pdflens-frontend
    ports:
      - "3000:80"
    # This loads the file for the container at runtime
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:
  chroma_data: